### ISSUE TITLE
Should we move devtools to Imports?

### ISSUE THREAD

**Issue by robertzk** [robertzk/lockbox#1]
Or just steal the `install_github` function like packrat did?

**Comment by kirillseva** [comment]
@importFrom devtools install_github?

**Comment by robertzk** [comment]
So much better, yes.

On Sat, Apr 4, 2015 at 4:57 PM, Kirill Sevastyanenko <
notifications@github.com> wrote:

> @importFrom devtools install_github?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/robertzk/lockbox/issues/1#issuecomment-89671304.

## 

-Robert Krzyzanowski

**Comment by kirillseva** [comment]
close?

**Comment by robertzk** [comment]
Addressed by https://github.com/robertzk/lockbox/commit/bc3d09c61a66cdff363db9b594f1f0ba130be18b
