### ISSUE TITLE
Drop unnecessary (potentially) masking exports

### ISSUE THREAD

**Issue by russellpierce** [robertzk/lockbox#106]
I see ... 
```
Attaching package: ‘lockbox’

The following object is masked from ‘package:stats’:

    setNames

The following objects are masked from ‘package:utils’:

    packageVersion, untar
```
... on initial load (R 3.4).  Is there a reason these three functions need to be exported?

**Comment by robertzk** [comment]
Agreed. I don't remember if that was intentional but I agree those should not need exporting.
