### ISSUE TITLE
end run around crappy Anaconda R install

### ISSUE THREAD

**Issue by shabbybanks** [robertzk/lockbox#109]
I am having a problem with `lockbox` perhaps related to similar problems I had trying [`packrat`](https://github.com/rstudio/packrat/issues/381): because the `R_PKGS_RECOMMENDED` field is not filled, `lockbox` gets confused. I am using the minimal `lockfile.yml`:

```yml
packages:
  -
    name: glmnet
    version: 2.0-10
```
I get the following errors on startup:
```

Retrieving dependency info....
....
Using dependency iterators 1.0.8
Installing dependency codetools from CRAN
ked and MD5 sums checked
Error : Invalid DESCRIPTION file

Invalid Priority field.
Packages with priorities 'base' or 'recommended' or 'defunct-base' must
already be known to R.

See section 'The DESCRIPTION file' in the 'Writing R Extensions'
manual.

ERROR: installing package DESCRIPTION failed for package ‘codetools’
* removing ‘/home/MYUSERNAME/.R/lockbox/.staging/codetools’
trying URL 'http://cran.r-project.org/src/contrib/codetools_0.2-15.tar.gz'
Content type 'application/x-gzip' length 12930 bytes (12 KB)
==================================================
downloaded 12 KB

ked and MD5 sums checked
Error : Invalid DESCRIPTION file

Invalid Priority field.
Packages with priorities 'base' or 'recommended' or 'defunct-base' must
already be known to R.

See section 'The DESCRIPTION file' in the 'Writing R Extensions'
manual.

ERROR: installing package DESCRIPTION failed for package ‘codetools’
* removing ‘/home/MYUSERNAME/.R/lockbox/.staging/codetools’

The downloaded source packages are in
        ‘/tmp/RtmpakM6PU/downloaded_packages’
ked and MD5 sums checked
Error : Invalid DESCRIPTION file

Invalid Priority field.
Packages with priorities 'base' or 'recommended' or 'defunct-base' must
already be known to R.

See section 'The DESCRIPTION file' in the 'Writing R Extensions'
manual.
ERROR: installing package DESCRIPTION failed for package ‘codetools’
* removing ‘/home/MYUSERNAME/.R/lockbox/.staging/codetools’
trying URL 'http://cran.r-project.org/src/contrib/codetools_0.2-15.tar.gz'
Content type 'application/x-gzip' length 12930 bytes (12 KB)
==================================================
downloaded 12 KB

ked and MD5 sums checked
Error : Invalid DESCRIPTION file

Invalid Priority field.
Packages with priorities 'base' or 'recommended' or 'defunct-base' must
already be known to R.

See section 'The DESCRIPTION file' in the 'Writing R Extensions'
manual.

ERROR: installing package DESCRIPTION failed for package ‘codetools’
* removing ‘/home/MYUSERNAME/.R/lockbox/.staging/codetools’

The downloaded source packages are in
        ‘/tmp/RtmpakM6PU/downloaded_packages’
Error in install_locked_package(locked_package) :
  Must have installed the package codetools of version ‘0.2.15’
```

FWIW, my session info is:
```
> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server release 6.7 (Santiago)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] graphics  grDevices datasets  stats     utils     methods   base

loaded via a namespace (and not attached):
[1] lockbox_0.2.4 tools_3.2.2   yaml_2.1.14   digest_0.6.12
```

**Comment by russellpierce** [comment]
Well that sounds like you've been on a frustration journey. :( Per CRAN, codetools should be included with the R binaries. What happens if you launch R and just load that package? What version shows up in sessionInfo()? I'm wondering if it was never there or if we're getting it because it needs to be updated. It seems like our DESCRIPTION parser doesn't like that codetools is special.

**Comment by kirillseva** [comment]
@shabbybanks want to try upgrading R to 3.4.0?

**Comment by shabbybanks** [comment]
@drknexus : `codetools` _is_ included with my distribution, which make this error rather mystifying. (Actually, I ran into similar issues with `packrat`; see the linked issue above.) Here I am in my home directory loading a bunch of packages:
```r
> getwd()
[1] "/blahblah/home/USERNAME"
> library(MASS)
> library(codetools)
> library(survival)
> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server release 6.7 (Santiago)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] survival_2.38-3  codetools_0.2-14 MASS_7.3-45      fortunes_1.5-4
[5] drat_0.1.2

loaded via a namespace (and not attached):
[1] tools_3.2.2   splines_3.2.2
```

**Comment by shabbybanks** [comment]
@kirillseva : hahaha! Great joke! :+1:  Actually, this is within the walls of a large institution where I have no administrative rights, and am lucky to have a 2 year old version of R. (The supported `python` on this machine is 2.6!) One suggestion on the [`packrat` issue](https://github.com/rstudio/packrat/issues/381) was to modify the `vars.mk` file which controls what is 'recommended'. Again, this is not possible.

**Comment by russellpierce** [comment]
@shabbybanks Yeah, but I see that you've got code tools 0.2-14 but in the install it is trying for `http://cran.r-project.org/src/contrib/codetools_0.2-15.tar.gz`.  

I bet one of the downstream dependencies of glmnet 2.0-10 is requiring the newer version of codetools.  Your best bet is to walk back the version of glmnet you use until you find a version that doesn't also need the new codetools.  Solving things on the lockbox end would require changing how the DESCRIPTION file is parsed, which is still perhaps a good goal and enough to leave the issue open - but perhaps unlikely to get movement until it affects someone else directly and they feel moved to fix it. ... I'm not even sure it is solvable - codetools might not be installable independent of its paired R binary.

YMMV, but I've found it possible in the past to install R without administrative rights.  You may have to jump through some hoops though and depending on your institution that may be a violation of policy.

**Comment by robertzk** [comment]
@kirillseva @drknexus Thank you for jumping in.

@shabbybanks My commiseration on the administrative constraints. I know how annoying that stuff can be!

I don't have the bandwidth to reproduce and investigate this at the moment, but if you have some time it would be helpful to make a public AWS AMI with a setup that matches yours and reproduces the problem. That will allow me to spin up an EC2 instance and debug from there. Thanks!

**Comment by shabbybanks** [comment]
@robertzk : I have no experience with AMI, but I could probably throw together a docker image very quickly. (At home! There's no docker in the walls of this institution!) Would that do?

**Comment by robertzk** [comment]
Yes, that would be perfect. 👍

**Comment by kirillseva** [comment]
also, try adding
```yaml
packages:
  -
    name: codetools
    version: 0.2-14
```
to your lockfile and see if this would resolve the issue? (just in case, put this before glmnet)

**Comment by shabbybanks** [comment]
@kirillseva ; Thanks for the suggestion. When I do that, `lockbox` tries to install `lattice` 0.20-35 and fails. I have 0.20-33 installed on my system. If I put a stanza for `lattice` in my `lockfile.yml` with that version number, I get the error:
```r
Error: Version maintenance of the following packages is not currently supported by lockbox: lattice.
```

**Comment by shabbybanks** [comment]
Reproducing the anaconda-based environment is a little tricky. It may take a few more nights.

**Comment by shabbychef** [comment]
I have isolated the problem in a docker container: https://hub.docker.com/r/shabbychef/dep_hell/builds/bsnrvpkh2jzfzlslcexya4d/
You can get it via:
```bash
docker pull shabbychef/dep_hell
docker run -it --rm shabbychef/dep_hell
```

**Comment by shabbybanks** [comment]
What he said.

**Comment by robertzk** [comment]
@shabbychef Thanks! I'll pull down the docker container sometime next week after our Q2 dust settles down and hopefully find a remedy.

**Comment by kevinushey** [comment]
The issue here is with the R installation being used: normally, R installations understand what the 'recommended' R packages (e.g. `MASS`); however, for whatever reason this Anaconda installation does not.

I believe the fix needs to occur within the version of R distributed by Anaconda, and I'm not aware of any other workarounds.

**Comment by russellpierce** [comment]
Is this clear to close then?

**Comment by kirillseva** [comment]
Kevin, in your anaconda R, what is the result of calling .libPaths() ?
Maybe the gotcha is there. Either that or something weird is happening with
anaconda R distribution.

You could also explicitly list all packages in your lockfile, so that no
dependency installation is needed, and all installs are "green" without any
"blue" ones

**Comment by shabbybanks** [comment]
There is definitely a deficiency with respect to this install of anaconda R (perhaps a local issue, or perhaps this packaging of R). I suspect nothing can be done for my case.
