### ISSUE TITLE
Lockbox appears to have unstated dependency on methods::is()

### ISSUE THREAD

**Issue by russellpierce** [robertzk/lockbox#112]
~/data-science-env/lockfiles/lockfile-v0.1.0.yml
```
packages:
  -
    name: plumber
    version: 0.3.2
    load: false
```

moo.R:
```
library(lockbox)
lockbox('~/data-science-env/lockfiles/lockfile-v0.1.0.yml')
print("moo")
library(plumber)
```

Console:
```
> Rscript moo.R
Retrieving dependency info...
Error in is(obj, "locked_package") : could not find function "is"
Calls: lockbox ... withCallingHandlers -> suppressMessages -> withCallingHandlers
Execution halted
```

**Comment by robertzk** [comment]
Thanks! We've had to [explicitly load](https://github.com/robertzk/lockbox/blob/master/tests/testthat/helper-random-dependencies.R#L48) `library(methods)` in batch situations before. I'll try to hunt down the stray calls.

**Comment by russellpierce** [comment]
I'd tried tweaking the doc string and Namespace for @importFrom for methods::is() but that didn't work. If you have spare time and a thought as to why  doesn't work, I'd love to hear it. Is it just that package:methods is special?

**Comment by robertzk** [comment]
The NAMESPACE file that's generated from the roxygen @importFrom should
copy `is` into the package's namespace. It probably has something to do
with the fact that the methods package is built in, although I'd have to
dig in a bit to understand why.
