### ISSUE TITLE
Versions with leading 0s incorrectly resolved

### ISSUE THREAD

**Issue by russellpierce** [robertzk/lockbox#124]
The error message is...
`Must have installed the package {package_name} of version '{version_missing_leading_zeros}'.  This error occurs even when the package version has been quoted in the yml lockfile.  This bug report might just fall under the class of thing that shouldn't happen in a civilized world (i.e. leading zeros in package version number components).  However, it is something I stumbled onto with an in-house development package so I thought I'd raise it here just in case we thought it was worth fixing.

**Comment by kirillseva** [comment]
Like this?
```
as.package_version('01.0.01')
[1] ‘1.0.1’
```

**Comment by kirillseva** [comment]
I hate to say it, but sounds like it's an R limitation, or an R feature if you will. The error happens because of how `base::as.package_version`works.

And for once I was willing to admit that there's a bug with how lockbox treats versions!

**Comment by peterhurford** [comment]
I agree that if R doesn't support it, we shouldn't support it, as much as I would like to annoy @kirillseva by hacking around this. ;)

**Comment by russellpierce** [comment]
Agreed. Thanks for looking in on it.
