### ISSUE TITLE
package:jsonlite used in devtools_substitutes.R but not in Imports or Suggests

### ISSUE THREAD

**Issue by russellpierce** [robertzk/lockbox#129]
As the title says... is this okay?  It seems to annoy CMD CHECK.

**Comment by peterhurford** [comment]
I think it's "okay" as in the package will still be functional, but it is not desirable from stability and maintainability standpoints. We should fix it.

**Comment by russellpierce** [comment]
Alright. Sounds good. jsonlite doesn't look too add any upstream dependencies so it shouldn't be a big deal. https://github.com/jeroen/jsonlite/blob/master/DESCRIPTION I'll probably be poking around in this codebase later this week. If nobody else jumps on it, then I'll fix it.

**Comment by robertzk** [comment]
Thanks @russellpierce , good point. [Fixed here](4927379d29afce87b704a13e693ae99a23cb3943). Feel free to re-open the issue if R CMD CHECK isn't happy.
