### ISSUE TITLE
Implement bundle clean

### ISSUE THREAD

**Issue by robertzk** [robertzk/lockbox#25]
The `lockbox` function can just keep a list of lockfiles it has ever encountered, iterate over them, and prune away versions not in any lockfile. This of course means switching to an older commit will re-install the older versions, but that is precisely the point of clean.

**Comment by kirillseva** [comment]
Why not just clean the whole directory? And when you restart R session, it will download correct versions

**Comment by robertzk** [comment]
Good idea. Maybe that should be lockbox destroy?

**Comment by kirillseva** [comment]
https://github.com/robertzk/lockbox/pull/31

**Comment by robertzk** [comment]
Done by emptybox. ^
