### ISSUE TITLE
Write some documentation regarding implementation details.

### ISSUE THREAD

**Issue by kirillseva** [robertzk/lockbox#3]
https://github.com/jimhester/covr/blob/master/vignettes/how_it_works.Rmd

**Comment by robertzk** [comment]
Heck yeah.

On Sat, Apr 4, 2015 at 4:57 PM, Kirill Sevastyanenko <
notifications@github.com> wrote:

> https://github.com/jimhester/covr/blob/master/vignettes/how_it_works.Rmd
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/robertzk/lockbox/issues/3.

## 

-Robert Krzyzanowski

**Comment by robertzk** [comment]
Does https://github.com/robertzk/lockbox/blob/master/vignettes/lockbox-libraries.Rmd work for you? @kirillseva
