### ISSUE TITLE
Lockbox may not work in RStudio

### ISSUE THREAD

**Issue by peterhurford** [robertzk/lockbox#35]

**Comment by robertzk** [comment]
Is there a stack trace of some sort?

**Comment by peterhurford** [comment]
No, it just fails to run.

**Comment by robertzk** [comment]
Rstudio might set its own working directory. Try changing the default directory to your project with the relevant `.Rprofile` that loads the lockfile.

http://stackoverflow.com/questions/22432344/how-do-you-change-the-default-directory-in-rstudio-or-r

**Comment by robertzk** [comment]
@peterhurford Is this still an issue?

**Comment by peterhurford** [comment]
I don't know, I never use RStudio.

**Comment by russellpierce** [comment]
YMMV but it doesn't seem to pose a problem on a reasonably current install of RStudio Server.  The Crayon bits don't render well, but the lockbox loads and seems to behave as expected.  Recommend that the issue be closed pending further error reports.

**Comment by robertzk** [comment]
@drknexus Thanks! Do you know of any approach to colorizing Rstudio console output?

**Comment by russellpierce** [comment]
Nothing off the top of my head, but I've seen rumblings that they are planning to prettify the console. The examples I saw included decimal alignment for sure, and I think colour as well. I have no idea if it'll end up being directly usable in the base R REPL or when to expect it.

Given infinite time and monkeys it would be great to skip the colorize of an RStudio session was detected, but that is so far down my mental list I'm not even opening an issue for it. :)
