### ISSUE TITLE
Some functions from packman may be useful for dependency computation

### ISSUE THREAD

**Issue by robertzk** [robertzk/lockbox#36]
https://github.com/hadley/packman/tree/master/R

**Comment by russellpierce** [comment]
Did you spot anything in particular?  Nothing jumped out at me.  Since the repo is 4 years stale, it doesn't seem likely that we'd be seeing much more development on it - we'd have to bring across whatever was useful and I didn't spot a license file over there.  Maybe more trouble than it is worth?

**Comment by robertzk** [comment]
@drknexus Agreed. Closing.
