### ISSUE TITLE
Delete unused package versions in the lockbox directory

### ISSUE THREAD

**Issue by khalidharun** [robertzk/lockbox#72]
When lockbox is used regularly, many version of packages get created a stay dormant in the file system and do nothing more than take up disk space.  It would be nice to have a utility to clean out all old versions and reclaim disk space.

**Comment by peterhurford** [comment]
@khalidharun Isn't that the point of lockbox, to allow you revert to older package versions easily?  Each package is usually only ~1MB at most, so I don't think it takes up too much disk space.

**Comment by kirillseva** [comment]
@khalidharun you can always do `lockbox::emptybox()` to clean up the package cache
